--INITIALISATION TABLE PERSONNE
INSERT INTO PERSONNE(USER_ID, NAME, FIRSTNAME, BIRTHDATE) values (1, 'Paul', 'Preboist', '1921-06-18');
INSERT INTO PERSONNE(USER_ID, NAME, FIRSTNAME, BIRTHDATE) values (2, 'Aroun', 'Tazzief', '1940-04-23');
INSERT INTO PERSONNE(USER_ID, NAME, FIRSTNAME, BIRTHDATE) values (3, 'Michel', 'Platini', '1953-05-16');
COMMIT;